//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace Exlibris.Rosetta.UpdateAIP.IEWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IEWebServicesBinding", Namespace="http://dps.exlibris.com/")]
    public partial class IEWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback generateFixityEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHeartBitOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIEOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIEMDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRevisionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateIEMDOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateMDOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateRepresentationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IEWebServices() {
            this.Url = global::Exlibris.Rosetta.UpdateAIP.Properties.Settings.Default.UpdateAIP_IEWebService_IEWebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event generateFixityEventCompletedEventHandler generateFixityEventCompleted;
        
        /// <remarks/>
        public event getHeartBitCompletedEventHandler getHeartBitCompleted;
        
        /// <remarks/>
        public event getIECompletedEventHandler getIECompleted;
        
        /// <remarks/>
        public event getIEMDCompletedEventHandler getIEMDCompleted;
        
        /// <remarks/>
        public event getMDCompletedEventHandler getMDCompleted;
        
        /// <remarks/>
        public event getRevisionStatusCompletedEventHandler getRevisionStatusCompleted;
        
        /// <remarks/>
        public event updateIEMDCompletedEventHandler updateIEMDCompleted;
        
        /// <remarks/>
        public event updateMDCompletedEventHandler updateMDCompleted;
        
        /// <remarks/>
        public event updateRepresentationCompletedEventHandler updateRepresentationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("generateFixityEventResponse", Namespace="http://dps.exlibris.com/")]
        public generateFixityEventResponse generateFixityEvent([System.Xml.Serialization.XmlElementAttribute("generateFixityEvent", Namespace="http://dps.exlibris.com/")] generateFixityEvent generateFixityEvent1) {
            object[] results = this.Invoke("generateFixityEvent", new object[] {
                        generateFixityEvent1});
            return ((generateFixityEventResponse)(results[0]));
        }
        
        /// <remarks/>
        public void generateFixityEventAsync(generateFixityEvent generateFixityEvent1) {
            this.generateFixityEventAsync(generateFixityEvent1, null);
        }
        
        /// <remarks/>
        public void generateFixityEventAsync(generateFixityEvent generateFixityEvent1, object userState) {
            if ((this.generateFixityEventOperationCompleted == null)) {
                this.generateFixityEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateFixityEventOperationCompleted);
            }
            this.InvokeAsync("generateFixityEvent", new object[] {
                        generateFixityEvent1}, this.generateFixityEventOperationCompleted, userState);
        }
        
        private void OngenerateFixityEventOperationCompleted(object arg) {
            if ((this.generateFixityEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateFixityEventCompleted(this, new generateFixityEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getHeartBitResponse", Namespace="http://dps.exlibris.com/")]
        public getHeartBitResponse getHeartBit([System.Xml.Serialization.XmlElementAttribute("getHeartBit", Namespace="http://dps.exlibris.com/")] getHeartBit getHeartBit1) {
            object[] results = this.Invoke("getHeartBit", new object[] {
                        getHeartBit1});
            return ((getHeartBitResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getHeartBitAsync(getHeartBit getHeartBit1) {
            this.getHeartBitAsync(getHeartBit1, null);
        }
        
        /// <remarks/>
        public void getHeartBitAsync(getHeartBit getHeartBit1, object userState) {
            if ((this.getHeartBitOperationCompleted == null)) {
                this.getHeartBitOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHeartBitOperationCompleted);
            }
            this.InvokeAsync("getHeartBit", new object[] {
                        getHeartBit1}, this.getHeartBitOperationCompleted, userState);
        }
        
        private void OngetHeartBitOperationCompleted(object arg) {
            if ((this.getHeartBitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHeartBitCompleted(this, new getHeartBitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getIEResponse", Namespace="http://dps.exlibris.com/")]
        public getIEResponse getIE([System.Xml.Serialization.XmlElementAttribute("getIE", Namespace="http://dps.exlibris.com/")] getIE getIE1) {
            object[] results = this.Invoke("getIE", new object[] {
                        getIE1});
            return ((getIEResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getIEAsync(getIE getIE1) {
            this.getIEAsync(getIE1, null);
        }
        
        /// <remarks/>
        public void getIEAsync(getIE getIE1, object userState) {
            if ((this.getIEOperationCompleted == null)) {
                this.getIEOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIEOperationCompleted);
            }
            this.InvokeAsync("getIE", new object[] {
                        getIE1}, this.getIEOperationCompleted, userState);
        }
        
        private void OngetIEOperationCompleted(object arg) {
            if ((this.getIECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIECompleted(this, new getIECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getIEMDResponse", Namespace="http://dps.exlibris.com/")]
        public getIEMDResponse getIEMD([System.Xml.Serialization.XmlElementAttribute("getIEMD", Namespace="http://dps.exlibris.com/")] getIEMD getIEMD1) {
            object[] results = this.Invoke("getIEMD", new object[] {
                        getIEMD1});
            return ((getIEMDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getIEMDAsync(getIEMD getIEMD1) {
            this.getIEMDAsync(getIEMD1, null);
        }
        
        /// <remarks/>
        public void getIEMDAsync(getIEMD getIEMD1, object userState) {
            if ((this.getIEMDOperationCompleted == null)) {
                this.getIEMDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIEMDOperationCompleted);
            }
            this.InvokeAsync("getIEMD", new object[] {
                        getIEMD1}, this.getIEMDOperationCompleted, userState);
        }
        
        private void OngetIEMDOperationCompleted(object arg) {
            if ((this.getIEMDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIEMDCompleted(this, new getIEMDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMDResponse", Namespace="http://dps.exlibris.com/")]
        public getMDResponse getMD([System.Xml.Serialization.XmlElementAttribute("getMD", Namespace="http://dps.exlibris.com/")] getMD getMD1) {
            object[] results = this.Invoke("getMD", new object[] {
                        getMD1});
            return ((getMDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMDAsync(getMD getMD1) {
            this.getMDAsync(getMD1, null);
        }
        
        /// <remarks/>
        public void getMDAsync(getMD getMD1, object userState) {
            if ((this.getMDOperationCompleted == null)) {
                this.getMDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMDOperationCompleted);
            }
            this.InvokeAsync("getMD", new object[] {
                        getMD1}, this.getMDOperationCompleted, userState);
        }
        
        private void OngetMDOperationCompleted(object arg) {
            if ((this.getMDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMDCompleted(this, new getMDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getRevisionStatusResponse", Namespace="http://dps.exlibris.com/")]
        public getRevisionStatusResponse getRevisionStatus([System.Xml.Serialization.XmlElementAttribute("getRevisionStatus", Namespace="http://dps.exlibris.com/")] getRevisionStatus getRevisionStatus1) {
            object[] results = this.Invoke("getRevisionStatus", new object[] {
                        getRevisionStatus1});
            return ((getRevisionStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getRevisionStatusAsync(getRevisionStatus getRevisionStatus1) {
            this.getRevisionStatusAsync(getRevisionStatus1, null);
        }
        
        /// <remarks/>
        public void getRevisionStatusAsync(getRevisionStatus getRevisionStatus1, object userState) {
            if ((this.getRevisionStatusOperationCompleted == null)) {
                this.getRevisionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRevisionStatusOperationCompleted);
            }
            this.InvokeAsync("getRevisionStatus", new object[] {
                        getRevisionStatus1}, this.getRevisionStatusOperationCompleted, userState);
        }
        
        private void OngetRevisionStatusOperationCompleted(object arg) {
            if ((this.getRevisionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRevisionStatusCompleted(this, new getRevisionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateIEMDResponse", Namespace="http://dps.exlibris.com/")]
        public updateIEMDResponse updateIEMD([System.Xml.Serialization.XmlElementAttribute("updateIEMD", Namespace="http://dps.exlibris.com/")] updateIEMD updateIEMD1) {
            object[] results = this.Invoke("updateIEMD", new object[] {
                        updateIEMD1});
            return ((updateIEMDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateIEMDAsync(updateIEMD updateIEMD1) {
            this.updateIEMDAsync(updateIEMD1, null);
        }
        
        /// <remarks/>
        public void updateIEMDAsync(updateIEMD updateIEMD1, object userState) {
            if ((this.updateIEMDOperationCompleted == null)) {
                this.updateIEMDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateIEMDOperationCompleted);
            }
            this.InvokeAsync("updateIEMD", new object[] {
                        updateIEMD1}, this.updateIEMDOperationCompleted, userState);
        }
        
        private void OnupdateIEMDOperationCompleted(object arg) {
            if ((this.updateIEMDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateIEMDCompleted(this, new updateIEMDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateMDResponse", Namespace="http://dps.exlibris.com/")]
        public updateMDResponse updateMD([System.Xml.Serialization.XmlElementAttribute("updateMD", Namespace="http://dps.exlibris.com/")] updateMD updateMD1) {
            object[] results = this.Invoke("updateMD", new object[] {
                        updateMD1});
            return ((updateMDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateMDAsync(updateMD updateMD1) {
            this.updateMDAsync(updateMD1, null);
        }
        
        /// <remarks/>
        public void updateMDAsync(updateMD updateMD1, object userState) {
            if ((this.updateMDOperationCompleted == null)) {
                this.updateMDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateMDOperationCompleted);
            }
            this.InvokeAsync("updateMD", new object[] {
                        updateMD1}, this.updateMDOperationCompleted, userState);
        }
        
        private void OnupdateMDOperationCompleted(object arg) {
            if ((this.updateMDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateMDCompleted(this, new updateMDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateRepresentationResponse", Namespace="http://dps.exlibris.com/")]
        public updateRepresentationResponse updateRepresentation([System.Xml.Serialization.XmlElementAttribute("updateRepresentation", Namespace="http://dps.exlibris.com/")] updateRepresentation updateRepresentation1) {
            object[] results = this.Invoke("updateRepresentation", new object[] {
                        updateRepresentation1});
            return ((updateRepresentationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateRepresentationAsync(updateRepresentation updateRepresentation1) {
            this.updateRepresentationAsync(updateRepresentation1, null);
        }
        
        /// <remarks/>
        public void updateRepresentationAsync(updateRepresentation updateRepresentation1, object userState) {
            if ((this.updateRepresentationOperationCompleted == null)) {
                this.updateRepresentationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateRepresentationOperationCompleted);
            }
            this.InvokeAsync("updateRepresentation", new object[] {
                        updateRepresentation1}, this.updateRepresentationOperationCompleted, userState);
        }
        
        private void OnupdateRepresentationOperationCompleted(object arg) {
            if ((this.updateRepresentationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateRepresentationCompleted(this, new updateRepresentationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class generateFixityEvent {
        
        private string pdsHandleField;
        
        private fixityEvent eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fixityEvent @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class fixityEvent {
        
        private string agentNameField;
        
        private string algorithmNameField;
        
        private string copyIdField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string filePidField;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string algorithmName {
            get {
                return this.algorithmNameField;
            }
            set {
                this.algorithmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string copyId {
            get {
                return this.copyIdField;
            }
            set {
                this.copyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filePid {
            get {
                return this.filePidField;
            }
            set {
                this.filePidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class updateRepresentationResponse {
        
        private long returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class representationContent {
        
        private string labelField;
        
        private string newFileField;
        
        private string oldFilePidField;
        
        private operation operationField;
        
        private bool operationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newFile {
            get {
                return this.newFileField;
            }
            set {
                this.newFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oldFilePid {
            get {
                return this.oldFilePidField;
            }
            set {
                this.oldFilePidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public operation operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationSpecified {
            get {
                return this.operationFieldSpecified;
            }
            set {
                this.operationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public enum operation {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        REPLACE,
        
        /// <remarks/>
        REMOVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class updateRepresentation {
        
        private string pdsHandleField;
        
        private string iePidField;
        
        private string repPidField;
        
        private string submissionReasonField;
        
        private representationContent[] representationContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iePid {
            get {
                return this.iePidField;
            }
            set {
                this.iePidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string repPid {
            get {
                return this.repPidField;
            }
            set {
                this.repPidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string submissionReason {
            get {
                return this.submissionReasonField;
            }
            set {
                this.submissionReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("representationContent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public representationContent[] representationContent {
            get {
                return this.representationContentField;
            }
            set {
                this.representationContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class updateMDResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class updateMD {
        
        private string pdsHandleField;
        
        private string pIDField;
        
        private metaData[] metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metaData[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class metaData {
        
        private string contentField;
        
        private string midField;
        
        private string subTypeField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mid {
            get {
                return this.midField;
            }
            set {
                this.midField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class updateIEMDResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class updateIEMD {
        
        private string pdsHandleField;
        
        private string iePIDField;
        
        private metaData[] metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iePID {
            get {
                return this.iePIDField;
            }
            set {
                this.iePIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metaData[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getRevisionStatusResponse {
        
        private string getRevisionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRevisionStatus {
            get {
                return this.getRevisionStatusField;
            }
            set {
                this.getRevisionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getRevisionStatus {
        
        private string pdsHandleField;
        
        private long revisionIDField;
        
        private bool revisionIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long revisionID {
            get {
                return this.revisionIDField;
            }
            set {
                this.revisionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revisionIDSpecified {
            get {
                return this.revisionIDFieldSpecified;
            }
            set {
                this.revisionIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getMDResponse {
        
        private string getMDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getMD {
            get {
                return this.getMDField;
            }
            set {
                this.getMDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getMD {
        
        private string pdsHandleField;
        
        private string pIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIEMDResponse {
        
        private string getIEMDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getIEMD {
            get {
                return this.getIEMDField;
            }
            set {
                this.getIEMDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIEMD {
        
        private string pdsHandleField;
        
        private string iePIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iePID {
            get {
                return this.iePIDField;
            }
            set {
                this.iePIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIEResponse {
        
        private string getIEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getIE {
            get {
                return this.getIEField;
            }
            set {
                this.getIEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIE {
        
        private string pdsHandleField;
        
        private string iePidField;
        
        private long flagsField;
        
        private bool flagsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdsHandle {
            get {
                return this.pdsHandleField;
            }
            set {
                this.pdsHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iePid {
            get {
                return this.iePidField;
            }
            set {
                this.iePidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flagsSpecified {
            get {
                return this.flagsFieldSpecified;
            }
            set {
                this.flagsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getHeartBitResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getHeartBit {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class generateFixityEventResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void generateFixityEventCompletedEventHandler(object sender, generateFixityEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateFixityEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateFixityEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public generateFixityEventResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((generateFixityEventResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getHeartBitCompletedEventHandler(object sender, getHeartBitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHeartBitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHeartBitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getHeartBitResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getHeartBitResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getIECompletedEventHandler(object sender, getIECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getIEResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getIEResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getIEMDCompletedEventHandler(object sender, getIEMDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIEMDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIEMDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getIEMDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getIEMDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getMDCompletedEventHandler(object sender, getMDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getMDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getMDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getRevisionStatusCompletedEventHandler(object sender, getRevisionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRevisionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRevisionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getRevisionStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getRevisionStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateIEMDCompletedEventHandler(object sender, updateIEMDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateIEMDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateIEMDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public updateIEMDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((updateIEMDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateMDCompletedEventHandler(object sender, updateMDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateMDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateMDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public updateMDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((updateMDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateRepresentationCompletedEventHandler(object sender, updateRepresentationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateRepresentationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateRepresentationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public updateRepresentationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((updateRepresentationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591