//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Exlibris.Rosetta.UpdateAIP.DeliveryAccessWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeliveryAccessWSBinding", Namespace="http://dps.exlibris.com/")]
    public partial class DeliveryAccessWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getBaseFileUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDnxDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getExtendedIEByDVSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFilePathByDvsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFullIEByDVSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHeartBitOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIEOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIEByDVSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetadataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DeliveryAccessWS() {
            this.Url = global::Exlibris.Rosetta.UpdateAIP.Properties.Settings.Default.UpdateAIP_DeliveryAccessWS_DeliveryAccessWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getBaseFileUrlCompletedEventHandler getBaseFileUrlCompleted;
        
        /// <remarks/>
        public event getCMSRecordCompletedEventHandler getCMSRecordCompleted;
        
        /// <remarks/>
        public event getDnxDocumentCompletedEventHandler getDnxDocumentCompleted;
        
        /// <remarks/>
        public event getExtendedIEByDVSCompletedEventHandler getExtendedIEByDVSCompleted;
        
        /// <remarks/>
        public event getFilePathByDvsCompletedEventHandler getFilePathByDvsCompleted;
        
        /// <remarks/>
        public event getFullIEByDVSCompletedEventHandler getFullIEByDVSCompleted;
        
        /// <remarks/>
        public event getHeartBitCompletedEventHandler getHeartBitCompleted;
        
        /// <remarks/>
        public event getIECompletedEventHandler getIECompleted;
        
        /// <remarks/>
        public event getIEByDVSCompletedEventHandler getIEByDVSCompleted;
        
        /// <remarks/>
        public event getMetadataCompletedEventHandler getMetadataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getBaseFileUrlResponse", Namespace="http://dps.exlibris.com/")]
        public getBaseFileUrlResponse getBaseFileUrl([System.Xml.Serialization.XmlElementAttribute("getBaseFileUrl", Namespace="http://dps.exlibris.com/")] getBaseFileUrl getBaseFileUrl1) {
            object[] results = this.Invoke("getBaseFileUrl", new object[] {
                        getBaseFileUrl1});
            return ((getBaseFileUrlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getBaseFileUrlAsync(getBaseFileUrl getBaseFileUrl1) {
            this.getBaseFileUrlAsync(getBaseFileUrl1, null);
        }
        
        /// <remarks/>
        public void getBaseFileUrlAsync(getBaseFileUrl getBaseFileUrl1, object userState) {
            if ((this.getBaseFileUrlOperationCompleted == null)) {
                this.getBaseFileUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBaseFileUrlOperationCompleted);
            }
            this.InvokeAsync("getBaseFileUrl", new object[] {
                        getBaseFileUrl1}, this.getBaseFileUrlOperationCompleted, userState);
        }
        
        private void OngetBaseFileUrlOperationCompleted(object arg) {
            if ((this.getBaseFileUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBaseFileUrlCompleted(this, new getBaseFileUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getCMSRecordResponse", Namespace="http://dps.exlibris.com/")]
        public getCMSRecordResponse getCMSRecord([System.Xml.Serialization.XmlElementAttribute("getCMSRecord", Namespace="http://dps.exlibris.com/")] getCMSRecord getCMSRecord1) {
            object[] results = this.Invoke("getCMSRecord", new object[] {
                        getCMSRecord1});
            return ((getCMSRecordResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSRecordAsync(getCMSRecord getCMSRecord1) {
            this.getCMSRecordAsync(getCMSRecord1, null);
        }
        
        /// <remarks/>
        public void getCMSRecordAsync(getCMSRecord getCMSRecord1, object userState) {
            if ((this.getCMSRecordOperationCompleted == null)) {
                this.getCMSRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSRecordOperationCompleted);
            }
            this.InvokeAsync("getCMSRecord", new object[] {
                        getCMSRecord1}, this.getCMSRecordOperationCompleted, userState);
        }
        
        private void OngetCMSRecordOperationCompleted(object arg) {
            if ((this.getCMSRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSRecordCompleted(this, new getCMSRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDnxDocumentResponse", Namespace="http://dps.exlibris.com/")]
        public getDnxDocumentResponse getDnxDocument([System.Xml.Serialization.XmlElementAttribute("getDnxDocument", Namespace="http://dps.exlibris.com/")] getDnxDocument getDnxDocument1) {
            object[] results = this.Invoke("getDnxDocument", new object[] {
                        getDnxDocument1});
            return ((getDnxDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getDnxDocumentAsync(getDnxDocument getDnxDocument1) {
            this.getDnxDocumentAsync(getDnxDocument1, null);
        }
        
        /// <remarks/>
        public void getDnxDocumentAsync(getDnxDocument getDnxDocument1, object userState) {
            if ((this.getDnxDocumentOperationCompleted == null)) {
                this.getDnxDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDnxDocumentOperationCompleted);
            }
            this.InvokeAsync("getDnxDocument", new object[] {
                        getDnxDocument1}, this.getDnxDocumentOperationCompleted, userState);
        }
        
        private void OngetDnxDocumentOperationCompleted(object arg) {
            if ((this.getDnxDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDnxDocumentCompleted(this, new getDnxDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getExtendedIEByDVSResponse", Namespace="http://dps.exlibris.com/")]
        public getExtendedIEByDVSResponse getExtendedIEByDVS([System.Xml.Serialization.XmlElementAttribute("getExtendedIEByDVS", Namespace="http://dps.exlibris.com/")] getExtendedIEByDVS getExtendedIEByDVS1) {
            object[] results = this.Invoke("getExtendedIEByDVS", new object[] {
                        getExtendedIEByDVS1});
            return ((getExtendedIEByDVSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getExtendedIEByDVSAsync(getExtendedIEByDVS getExtendedIEByDVS1) {
            this.getExtendedIEByDVSAsync(getExtendedIEByDVS1, null);
        }
        
        /// <remarks/>
        public void getExtendedIEByDVSAsync(getExtendedIEByDVS getExtendedIEByDVS1, object userState) {
            if ((this.getExtendedIEByDVSOperationCompleted == null)) {
                this.getExtendedIEByDVSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExtendedIEByDVSOperationCompleted);
            }
            this.InvokeAsync("getExtendedIEByDVS", new object[] {
                        getExtendedIEByDVS1}, this.getExtendedIEByDVSOperationCompleted, userState);
        }
        
        private void OngetExtendedIEByDVSOperationCompleted(object arg) {
            if ((this.getExtendedIEByDVSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExtendedIEByDVSCompleted(this, new getExtendedIEByDVSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getFilePathByDvsResponse", Namespace="http://dps.exlibris.com/")]
        public getFilePathByDvsResponse getFilePathByDvs([System.Xml.Serialization.XmlElementAttribute("getFilePathByDvs", Namespace="http://dps.exlibris.com/")] getFilePathByDvs getFilePathByDvs1) {
            object[] results = this.Invoke("getFilePathByDvs", new object[] {
                        getFilePathByDvs1});
            return ((getFilePathByDvsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getFilePathByDvsAsync(getFilePathByDvs getFilePathByDvs1) {
            this.getFilePathByDvsAsync(getFilePathByDvs1, null);
        }
        
        /// <remarks/>
        public void getFilePathByDvsAsync(getFilePathByDvs getFilePathByDvs1, object userState) {
            if ((this.getFilePathByDvsOperationCompleted == null)) {
                this.getFilePathByDvsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFilePathByDvsOperationCompleted);
            }
            this.InvokeAsync("getFilePathByDvs", new object[] {
                        getFilePathByDvs1}, this.getFilePathByDvsOperationCompleted, userState);
        }
        
        private void OngetFilePathByDvsOperationCompleted(object arg) {
            if ((this.getFilePathByDvsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFilePathByDvsCompleted(this, new getFilePathByDvsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getFullIEByDVSResponse", Namespace="http://dps.exlibris.com/")]
        public getFullIEByDVSResponse getFullIEByDVS([System.Xml.Serialization.XmlElementAttribute("getFullIEByDVS", Namespace="http://dps.exlibris.com/")] getFullIEByDVS getFullIEByDVS1) {
            object[] results = this.Invoke("getFullIEByDVS", new object[] {
                        getFullIEByDVS1});
            return ((getFullIEByDVSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getFullIEByDVSAsync(getFullIEByDVS getFullIEByDVS1) {
            this.getFullIEByDVSAsync(getFullIEByDVS1, null);
        }
        
        /// <remarks/>
        public void getFullIEByDVSAsync(getFullIEByDVS getFullIEByDVS1, object userState) {
            if ((this.getFullIEByDVSOperationCompleted == null)) {
                this.getFullIEByDVSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFullIEByDVSOperationCompleted);
            }
            this.InvokeAsync("getFullIEByDVS", new object[] {
                        getFullIEByDVS1}, this.getFullIEByDVSOperationCompleted, userState);
        }
        
        private void OngetFullIEByDVSOperationCompleted(object arg) {
            if ((this.getFullIEByDVSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFullIEByDVSCompleted(this, new getFullIEByDVSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getHeartBitResponse", Namespace="http://dps.exlibris.com/")]
        public getHeartBitResponse getHeartBit([System.Xml.Serialization.XmlElementAttribute("getHeartBit", Namespace="http://dps.exlibris.com/")] getHeartBit getHeartBit1) {
            object[] results = this.Invoke("getHeartBit", new object[] {
                        getHeartBit1});
            return ((getHeartBitResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getHeartBitAsync(getHeartBit getHeartBit1) {
            this.getHeartBitAsync(getHeartBit1, null);
        }
        
        /// <remarks/>
        public void getHeartBitAsync(getHeartBit getHeartBit1, object userState) {
            if ((this.getHeartBitOperationCompleted == null)) {
                this.getHeartBitOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHeartBitOperationCompleted);
            }
            this.InvokeAsync("getHeartBit", new object[] {
                        getHeartBit1}, this.getHeartBitOperationCompleted, userState);
        }
        
        private void OngetHeartBitOperationCompleted(object arg) {
            if ((this.getHeartBitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHeartBitCompleted(this, new getHeartBitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getIEResponse", Namespace="http://dps.exlibris.com/")]
        public getIEResponse getIE([System.Xml.Serialization.XmlElementAttribute("getIE", Namespace="http://dps.exlibris.com/")] getIE getIE1) {
            object[] results = this.Invoke("getIE", new object[] {
                        getIE1});
            return ((getIEResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getIEAsync(getIE getIE1) {
            this.getIEAsync(getIE1, null);
        }
        
        /// <remarks/>
        public void getIEAsync(getIE getIE1, object userState) {
            if ((this.getIEOperationCompleted == null)) {
                this.getIEOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIEOperationCompleted);
            }
            this.InvokeAsync("getIE", new object[] {
                        getIE1}, this.getIEOperationCompleted, userState);
        }
        
        private void OngetIEOperationCompleted(object arg) {
            if ((this.getIECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIECompleted(this, new getIECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getIEByDVSResponse", Namespace="http://dps.exlibris.com/")]
        public getIEByDVSResponse getIEByDVS([System.Xml.Serialization.XmlElementAttribute("getIEByDVS", Namespace="http://dps.exlibris.com/")] getIEByDVS getIEByDVS1) {
            object[] results = this.Invoke("getIEByDVS", new object[] {
                        getIEByDVS1});
            return ((getIEByDVSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getIEByDVSAsync(getIEByDVS getIEByDVS1) {
            this.getIEByDVSAsync(getIEByDVS1, null);
        }
        
        /// <remarks/>
        public void getIEByDVSAsync(getIEByDVS getIEByDVS1, object userState) {
            if ((this.getIEByDVSOperationCompleted == null)) {
                this.getIEByDVSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIEByDVSOperationCompleted);
            }
            this.InvokeAsync("getIEByDVS", new object[] {
                        getIEByDVS1}, this.getIEByDVSOperationCompleted, userState);
        }
        
        private void OngetIEByDVSOperationCompleted(object arg) {
            if ((this.getIEByDVSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIEByDVSCompleted(this, new getIEByDVSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMetadataResponse", Namespace="http://dps.exlibris.com/")]
        public getMetadataResponse getMetadata([System.Xml.Serialization.XmlElementAttribute("getMetadata", Namespace="http://dps.exlibris.com/")] getMetadata getMetadata1) {
            object[] results = this.Invoke("getMetadata", new object[] {
                        getMetadata1});
            return ((getMetadataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMetadataAsync(getMetadata getMetadata1) {
            this.getMetadataAsync(getMetadata1, null);
        }
        
        /// <remarks/>
        public void getMetadataAsync(getMetadata getMetadata1, object userState) {
            if ((this.getMetadataOperationCompleted == null)) {
                this.getMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetadataOperationCompleted);
            }
            this.InvokeAsync("getMetadata", new object[] {
                        getMetadata1}, this.getMetadataOperationCompleted, userState);
        }
        
        private void OngetMetadataOperationCompleted(object arg) {
            if ((this.getMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetadataCompleted(this, new getMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getBaseFileUrl {
        
        private string dvsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getMetadataResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getMetadata {
        
        private string dvsField;
        
        private string pidField;
        
        private string mdTypeField;
        
        private string mdSubTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mdType {
            get {
                return this.mdTypeField;
            }
            set {
                this.mdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mdSubType {
            get {
                return this.mdSubTypeField;
            }
            set {
                this.mdSubTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIEByDVSResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIEByDVS {
        
        private string dvsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIEResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getIE {
        
        private string arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getHeartBitResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getHeartBit {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getFullIEByDVSResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getFullIEByDVS {
        
        private string dvsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getFilePathByDvsResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getFilePathByDvs {
        
        private string dvsField;
        
        private string pidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getExtendedIEByDVSResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getExtendedIEByDVS {
        
        private string dvsField;
        
        private long flagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getDnxDocumentResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getDnxDocument {
        
        private string dvsField;
        
        private string pidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getCMSRecordResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getCMSRecord {
        
        private string dvsField;
        
        private string iePIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dvs {
            get {
                return this.dvsField;
            }
            set {
                this.dvsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iePID {
            get {
                return this.iePIDField;
            }
            set {
                this.iePIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dps.exlibris.com/")]
    public partial class getBaseFileUrlResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getBaseFileUrlCompletedEventHandler(object sender, getBaseFileUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBaseFileUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBaseFileUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getBaseFileUrlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getBaseFileUrlResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getCMSRecordCompletedEventHandler(object sender, getCMSRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getCMSRecordResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getCMSRecordResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getDnxDocumentCompletedEventHandler(object sender, getDnxDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDnxDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDnxDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getDnxDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getDnxDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getExtendedIEByDVSCompletedEventHandler(object sender, getExtendedIEByDVSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExtendedIEByDVSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExtendedIEByDVSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getExtendedIEByDVSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getExtendedIEByDVSResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getFilePathByDvsCompletedEventHandler(object sender, getFilePathByDvsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFilePathByDvsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFilePathByDvsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getFilePathByDvsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getFilePathByDvsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getFullIEByDVSCompletedEventHandler(object sender, getFullIEByDVSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFullIEByDVSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFullIEByDVSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getFullIEByDVSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getFullIEByDVSResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getHeartBitCompletedEventHandler(object sender, getHeartBitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHeartBitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHeartBitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getHeartBitResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getHeartBitResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getIECompletedEventHandler(object sender, getIECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getIEResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getIEResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getIEByDVSCompletedEventHandler(object sender, getIEByDVSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIEByDVSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIEByDVSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getIEByDVSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getIEByDVSResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getMetadataCompletedEventHandler(object sender, getMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getMetadataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getMetadataResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591